### ISSUE TITLE
How can send password?

### ISSUE THREAD

**Issue by alizowghi** [jcs224/faktory_worker_php5#1]
Hi
How can i set password in client??
$socket = stream_socket_client("tcp://{$this->faktoryHost}:{$this->faktoryPort}", $errno, $errstr, 30);

**Comment by jcs224** [comment]
Ah, I haven't put that ability in yet. PRs always welcome, of course.

**Comment by jcs224** [comment]
@alizowghi you can now add the Faktory server password as a third argument to a new `FaktoryClient` instance. Not tested with TLS.
